RKonnect/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('membersApp/', include('membersApp.urls')),
    path('membersProfiles/', include('membersProfiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.profiles, name = 'profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),
    
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile
# Create your models here.



class Project(models.Model):
    owner = models.ForeignKey(Profile, null = True, blank = True, on_delete = models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default = 'Logo.png')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank = True)
    vote_total = models.IntegerField(default = 0, null = True, blank = True)
    vote_ratio = models.IntegerField(default = 0, null = True, blank = True)
    created = models.DateField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    #owner = 
    project = models.ForeignKey(Project, on_delete = models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices = VOTE_TYPE)
    created = models.DateField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return self.value
    
class Tag(models.Model):
    name = models.CharField(max_length = 200)
    created = models.DateField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return self.name
    


users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/Capture2.PNG')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)  # Corrected the field name
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):  
        return str(self.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null = True, blank = True)
    name = models.CharField(max_length=200, blank = True, null = True)
    description = models.TextField(null = True, blank = True)
    created = models.DateField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):  
        return str(self.name)
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Profile
# Create your views here.

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)

def userProfile(request, pk):
    profile = Profile.objects.get(id = pk)

    topSkills = profile.skill_set.exclude(description= "")
    otherSkills = profile.skill_set.filter(description= "")
    context = {'profile': profile, 'topSkills': topSkills, 'otherSkills': otherSkills}
    return render(request, 'users/user-profile.html', context)


users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
<main class="home">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>CONNECT WITH <span>Young Minds</span></h2>
        <h2>FROM AROUND South Africa</h2>
      </div>

      <div class="hero-section__search">
        <form class="form" action="#" method="get">
          <div class="form__field">
            <label for="formInput#search">Search Young Professionals</label>
            <input class="input input--text" id="formInput#search" type="text" name="text"
              placeholder="Search by developer name" />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="devlist">
    <div class="container">
      <div class="grid grid--three">

        {% for profile in profiles %}
        <div class="column card">
          <div class="dev">
            <a href="{% url 'user-profile' profile.id %}" class="card__body">
              <div class="dev__profile">
                <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                <div class="dev__meta">
                  <h3>{{ profile.name }}</h3>
                  <h5>{{profile.short_intro| slice:"60"}}</h5>
                </div>
              </div>
              <p class="dev__info">
                {{ profile.bio| slice:"100" }}
              <div class="dev__skills">

                {% for skill in profile.skill_set.all %}
                <span class="tag tag--pill tag--main">
                  <small>{{ skill }}</small>
                </span>
                {% endfor %}
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</main>
{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}


{% block content %}
<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                
                {% if profile.social_github %}
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_github %}
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_github %}
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About {{ profile.name }}</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">

                {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">{{ skill.description }}</p>
              </div>
              {% endfor %}
             
            

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for skill in otherSkill %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Figma</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

                {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.tittle }}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">{{ project.owner.name }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                        Feedback (Total Votes: {{ project.vote_total }})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{ tag }}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}              

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}